---

- name: NTP installed?
  yum: 
    name: ntpd
    state: present

- name: NTP configuration
  template:
    src: ntpd.conf.j2
    dest: /etc/ntpd.conf
 
- name: NTP enabled?
  service: 
    name: ntpd
    state: started
    enabled: yes
