---
- hosts: all
  ignore_errors: true

  vars:

    ansible-major-version: 2

    # schedule is fed directly to cron
    schedule: '*/15 * * * *'

    # User to run ansible-pull as from cron
    cron_user: root

    # File that ansible will use for logs
    logfile: /var/log/ansible-pull.log

    # Directory to where repository will be cloned
    workdir: /var/lib/ansible/local

    # ** Repository to check out **
    # ** must contain a local.yml file at top level **
    repo_url: https://github.com/ffirg/ansible-pull

  tasks:

   - name: Enable a RHSM repository
     rhsm_repository:
       name: "rhel-7-server-ansible-{{ansible-major-version}}-rpms"

    - name: Install ansible
      yum: pkg=ansible state=installed

    - name: Create local directory to work from
      file: path={{workdir}} state=directory owner=root group=root mode=0751

    - name: Create crontab entry to clone/pull git repository
      template: src=templates/etc_cron.d_ansible-pull.j2 dest=/etc/cron.d/ansible-pull owner=root group=root mode=0644

    - name: Create logrotate entry for ansible-pull.log
      template: src=templates/etc_logrotate.d_ansible-pull.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644