---

- name: NTP installed?
  yum: 
    name: ntp
    state: present

- name: NTP configuration
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
 
- name: NTP enabled?
  service: 
    name: ntpd
    enabled: yes

  notify:
    - restart ntpd
    
