---

- name: Get platform environment
  debug: 
    msg: "This is a {{ platform_type }} platform"
    
- name: Baseline user accounts
  user: 
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid }}"
    state: present
    append: yes
  loop:
    - { name: 'phil', groups: 'users, wheel', comment: 'Phil Griffiths', uid: '1000' }
    - { name: 'fred', groups: 'users', comment: 'Fred Bloggs', uid: '1001' }
    - { name: 'ansible', groups: 'ansible', comment: 'Ansible Runtime', uid: '10000' }

  tags:
    - users

- name: Core firewall ports
  firewalld: 
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 22/tcp
    - 443/tcp
  notify:
    "restart firewall"
  tags:
    - firewall
    

