---

- name: Mandatory user accounts
  user: name={{ item.name }} state=present groups={{ item.groups }}
  with_items:
    - {name: 'ansible', groups: 'wheel' }
    - {name: 'fred', groups: 'wheel' }
    - {name: 'phil', groups: 'wheel' }
  tags:
    - users

- name: Core firewall ports
  firewalld: port={{ item }} permanent=true state=enabled
  with_items:
    - 22/tcp
    - 443/tcp
  notify:
    "restart firewall"
  tags:
    - firewall
    

