---

- name: Mandatory user accounts
  user: 
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid }}"
    state: present
    apend: yes
  loop:
    - { name: 'ansible', groups: 'wheel', comment: 'Ansible Runtime', uid: '1000' }
    - { name: 'fred', groups: 'wheel', comment: 'Fred Bloggs', uid: '1001' }
    - { name: 'phil', groups: 'wheel', comment: 'Phil Griffiths', uid: '1002' }
  tags:
    - users

- name: Core firewall ports
  firewalld: 
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 22/tcp
    - 443/tcp
  notify:
    "restart firewall"
  tags:
    - firewall
    

